product_category:
    path:     /
    defaults: { _controller: "AMZProductBundle:Category:index" }

product_category_show:
    path:     /{id}/show
    defaults: { _controller: "AMZProductBundle:Category:show" }

product_category_new:
    path:     /new
    defaults: { _controller: "AMZProductBundle:Category:new" }

product_category_create:
    path:     /create
    defaults: { _controller: "AMZProductBundle:Category:create" }
    requirements: { _method: post }

product_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "AMZProductBundle:Category:edit" }

product_category_update:
    path:     /{id}/update
    defaults: { _controller: "AMZProductBundle:Category:update" }
    requirements: { _method: post|put }

product_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "AMZProductBundle:Category:delete" }
    requirements: { _method: post|delete }
